name: Run unittests

on:
  push:
    tags-ignore:
      - '*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: pip3 install .
      - name: Run unittests
        run: python3 -m unittest discover