name: Release dataverk

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install dependencies
      run: pip3 install .
    - name: Run unittests
      run: python3 -m unittest discover

  update-version:
    name: Set dataverk version in setup.py to release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Update version
        run: |
          export VERSION=$(echo ${{ github.ref }} | sed "s~refs/tags/~~")
          sed -i "s~version=.*~version='$VERSION',~g" setup.py
      - name: Commit to repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: "Update dataverk version in setup.py"
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git fetch
          git checkout master
          git add setup.py
          git diff --quiet && git diff --staged --quiet || (git pull origin master; git commit -m "$COMMIT_MSG"; git push origin master)

  release-pypi:
    name: Release pypi
    needs: [test, update-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install twine
        run: pip3 install twine --user
      - name: Build release
        run: python3 setup.py sdist bdist_wheel
      - name: publish pypi
        run: python -m twine upload -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }} dist/*
